name: Hello World

on:
  push

jobs:
  echo-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Echo text
        run: echo "Hello, World!"
